# --------------------- #
#   Main Configs
# --------------------- #
url:  
title: 
author: 
# List categories here, not tags
categories: [blog]

permalink: /:categories/:title

twitter:
googleplus:


# Change example to yours
disqus_shortname: example

# --------------------- #
#   Jekyll & Plugin 
# --------------------- #

markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    
